//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCore.Data.Context
{
    using Microsoft.EntityFrameworkCore;
    using OneCore.Data.Entities;

    public partial class OneCoreEntities : Microsoft.EntityFrameworkCore.DbContext
    {
        public OneCoreEntities(DbContextOptions<OneCoreEntities> options)
            : base(options)
        {
        }


        public virtual Microsoft.EntityFrameworkCore.DbSet<User> User { get; set; }
    }
}
