//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCore.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string userSystem { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> sexo { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
